// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppMvcCore.Data;

namespace WebAppMvcCore.Migrations
{
    [DbContext(typeof(WebAppMvcCoreContext))]
    [Migration("20201210121456_updateDB")]
    partial class updateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppMvcCore.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("WebAppMvcCore.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("SellerIdId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("SellerIdId");

                    b.ToTable("SalesRecords");
                });

            modelBuilder.Entity("WebAppMvcCore.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BaseSalary");

                    b.Property<DateTime>("BirthDate");

                    b.Property<int?>("DepartmentIdId");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentIdId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("WebAppMvcCore.Models.SalesRecord", b =>
                {
                    b.HasOne("WebAppMvcCore.Models.Seller", "SellerId")
                        .WithMany("SalesRecords")
                        .HasForeignKey("SellerIdId");
                });

            modelBuilder.Entity("WebAppMvcCore.Models.Seller", b =>
                {
                    b.HasOne("WebAppMvcCore.Models.Department", "DepartmentId")
                        .WithMany("Sellers")
                        .HasForeignKey("DepartmentIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
